const ZH_PREFERENCE_LABELS: Record<string, string> = {
  locale: "界面语言",
  save_path: "默认保存路径",
  temp_path_enabled: "启用未完成文件目录",
  temp_path: "未完成文件保存路径",
  scan_dirs: "自动监控目录",
  export_dir: "复制种子文件到指定目录",
  export_dir_fin: "下载完成后复制种子文件到指定目录",
  create_subfolder_enabled: "创建种子名称子目录",
  start_paused_enabled: "添加种子后保持停止",
  preallocate_all: "预分配所有文件空间",
  incomplete_files_ext: "未完成文件添加 .!qB 后缀",
  auto_tmm_enabled: "启用自动种子管理",
  torrent_changed_tmm_enabled: "种子变化时重新定位文件",
  save_path_changed_tmm_enabled: "默认路径变化时重新定位文件",
  category_changed_tmm_enabled: "分类变化时重新定位文件",
  queueing_enabled: "启用种子队列",
  max_active_downloads: "最大活动下载数",
  max_active_uploads: "最大活动做种数",
  max_active_torrents: "最大活动种子数",
  dont_count_slow_torrents: "慢速种子不计入队列限制",
  slow_torrent_dl_rate_threshold: "慢速下载判定速度",
  slow_torrent_ul_rate_threshold: "慢速上传判定速度",
  slow_torrent_inactive_timer: "慢速种子判定时间",
  max_ratio_enabled: "启用分享率限制",
  max_ratio: "最大分享率",
  max_ratio_act: "达到分享率限制后的操作",
  max_seeding_time_enabled: "启用做种时间限制",
  max_seeding_time: "最长做种时间",
  max_seeding_time_limit_act: "达到做种时间限制后的操作",
  listen_port: "传入连接监听端口",
  upnp: "启用 UPnP / NAT-PMP 端口映射",
  random_port: "启动时随机选择监听端口",
  dl_limit: "全局下载速度限制",
  up_limit: "全局上传速度限制",
  alt_dl_limit: "备用下载速度限制",
  alt_up_limit: "备用上传速度限制",
  scheduler_enabled: "启用备用速度计划",
  schedule_from_hour: "计划开始小时",
  schedule_from_min: "计划开始分钟",
  schedule_to_hour: "计划结束小时",
  schedule_to_min: "计划结束分钟",
  scheduler_days: "备用速度计划日期",
  dht: "启用分布式哈希表（DHT）",
  pex: "启用用户交换（PeX）",
  lsd: "启用本地用户发现（LSD）",
  encryption: "连接加密模式",
  anonymous_mode: "启用匿名模式",
  proxy_type: "代理类型",
  proxy_ip: "代理服务器地址",
  proxy_port: "代理服务器端口",
  proxy_auth_enabled: "启用代理身份验证",
  proxy_username: "代理用户名",
  proxy_password: "代理密码",
  proxy_peer_connections: "通过代理连接用户",
  proxy_torrents_only: "仅将代理用于种子连接",
  ip_filter_enabled: "启用 IP 过滤",
  ip_filter_path: "IP 过滤规则文件",
  ip_filter_trackers: "将 IP 过滤应用到 Tracker",
  banned_IPs: "已封禁的 IP 地址",
  add_trackers_enabled: "自动添加 Tracker",
  add_trackers: "自动添加的 Tracker 列表",
  announce_to_all_tiers: "向所有 Tracker 层级汇报",
  announce_to_all_trackers: "向所有 Tracker 汇报",
  announce_ip: "向 Tracker 汇报的 IP 地址",
  web_ui_address: "WebUI 监听地址",
  web_ui_port: "WebUI 监听端口",
  web_ui_username: "WebUI 用户名",
  web_ui_password: "WebUI 密码",
  web_ui_upnp: "为 WebUI 启用 UPnP / NAT-PMP",
  web_ui_csrf_protection_enabled: "启用 WebUI 跨站请求伪造防护",
  web_ui_clickjacking_protection_enabled: "启用 WebUI 点击劫持防护",
  web_ui_host_header_validation_enabled: "启用 WebUI 主机头验证",
  web_ui_domain_list: "WebUI 允许的域名列表",
  web_ui_secure_cookie_enabled: "启用 WebUI 安全 Cookie",
  web_ui_max_auth_fail_count: "WebUI 最大登录失败次数",
  web_ui_ban_duration: "WebUI 登录封禁时长",
  web_ui_session_timeout: "WebUI 会话超时时间",
  alternative_webui_enabled: "启用备用 WebUI",
  alternative_webui_path: "备用 WebUI 文件路径",
  use_https: "启用 HTTPS",
  ssl_key: "HTTPS 私钥路径",
  ssl_cert: "HTTPS 证书路径",
  bypass_local_auth: "本机访问跳过身份验证",
  bypass_auth_subnet_whitelist_enabled: "允许指定网段跳过身份验证",
  bypass_auth_subnet_whitelist: "免身份验证网段白名单",
  dyndns_enabled: "启用动态域名服务",
  dyndns_service: "动态域名服务商",
  dyndns_username: "动态域名用户名",
  dyndns_password: "动态域名密码",
  dyndns_domain: "动态域名",
  rss_processing_enabled: "启用 RSS 种子下载器",
  rss_refresh_interval: "RSS 刷新间隔",
  rss_max_articles_per_feed: "每个 RSS 源最大文章数",
  rss_auto_downloading_enabled: "启用 RSS 自动下载",
  rss_download_repack_proper_episodes: "下载重发版与修正版剧集",
  mail_notification_enabled: "启用邮件通知",
  mail_notification_sender: "邮件通知发件人",
  mail_notification_email: "邮件通知收件人",
  mail_notification_smtp: "邮件服务器地址",
  mail_notification_ssl_enabled: "邮件服务器启用 SSL",
  mail_notification_auth_enabled: "邮件服务器启用身份验证",
  mail_notification_username: "邮件服务器用户名",
  mail_notification_password: "邮件服务器密码",
  autorun_enabled: "种子完成后运行外部程序",
  autorun_program: "种子完成后运行的程序",
  recheck_completed_torrents: "完成后重新校验种子",
  resolve_peer_countries: "解析用户所在国家或地区",
  refresh_interval: "界面数据刷新间隔",
  save_resume_data_interval: "保存恢复数据的间隔",
  async_io_threads: "异步输入输出线程数",
  hashing_threads: "哈希校验线程数",
  file_pool_size: "文件池大小",
  disk_cache: "磁盘缓存大小",
  disk_cache_ttl: "磁盘缓存保留时间",
  disk_queue_size: "磁盘队列大小",
  enable_os_cache: "启用操作系统磁盘缓存",
  enable_coalesce_read_write: "合并磁盘读写操作",
  enable_piece_extent_affinity: "启用分片范围亲和性",
  memory_working_set_limit: "内存工作集限制",
  outgoing_ports_min: "传出连接最小端口",
  outgoing_ports_max: "传出连接最大端口",
  max_connec: "全局最大连接数",
  max_connec_per_torrent: "单个种子最大连接数",
  max_uploads: "全局最大上传槽位数",
  max_uploads_per_torrent: "单个种子最大上传槽位数",
  socket_backlog_size: "套接字等待队列大小",
  send_buffer_watermark: "发送缓冲区上限",
  send_buffer_low_watermark: "发送缓冲区下限",
  send_buffer_watermark_factor: "发送缓冲区增长系数",
  request_queue_size: "请求队列大小",
  peer_tos: "用户连接服务类型标记",
  peer_turnover: "用户连接轮换比例",
  peer_turnover_cutoff: "用户连接轮换阈值",
  peer_turnover_interval: "用户连接轮换间隔",
  bittorrent_protocol: "BitTorrent 传输协议",
  limit_utp_rate: "将速度限制应用到 µTP",
  limit_tcp_overhead: "将速度限制应用到 TCP 开销",
  limit_lan_peers: "将速度限制应用到局域网用户",
  utp_tcp_mixed_mode: "µTP 与 TCP 混合模式算法",
  upload_choking_algorithm: "上传阻塞算法",
  upload_slots_behavior: "上传槽位分配方式",
  stop_tracker_timeout: "停止 Tracker 的超时时间",
  enable_embedded_tracker: "启用内置 Tracker",
  embedded_tracker_port: "内置 Tracker 端口",
}

const ZH_TOKEN_LABELS: Record<string, string> = {
  enabled: "启用",
  disabled: "禁用",
  path: "路径",
  port: "端口",
  address: "地址",
  username: "用户名",
  password: "密码",
  interval: "间隔",
  timeout: "超时",
  limit: "限制",
  limits: "限制",
  max: "最大",
  min: "最小",
  download: "下载",
  upload: "上传",
  torrents: "种子",
  torrent: "种子",
  peers: "用户",
  peer: "用户",
  queue: "队列",
  cache: "缓存",
  disk: "磁盘",
  network: "网络",
  connection: "连接",
  connections: "连接",
  notification: "通知",
  authentication: "身份验证",
  auth: "身份验证",
  protection: "防护",
  required: "需要",
  auto: "自动",
  random: "随机",
  default: "默认",
  alternative: "备用",
  secure: "安全",
  local: "本地",
  global: "全局",
  ratio: "分享率",
  seeding: "做种",
  time: "时间",
  hours: "小时",
  minutes: "分钟",
  days: "日期",
  threads: "线程数",
  size: "大小",
  mode: "模式",
  type: "类型",
  program: "程序",
  processing: "处理",
}

function humanizeEnglishKey(key: string): string {
  return key
    .split("_")
    .filter(Boolean)
    .map((token) => token.charAt(0).toUpperCase() + token.slice(1))
    .join(" ")
}

function humanizeChineseKey(key: string): string {
  const translated = key
    .split("_")
    .filter(Boolean)
    .map((token) => ZH_TOKEN_LABELS[token] ?? token.toUpperCase())
    .join(" · ")
  return `高级设置：${translated}`
}

export function getPreferenceLabel(key: string, locale: "en" | "zh"): string {
  if (locale === "zh") return ZH_PREFERENCE_LABELS[key] ?? humanizeChineseKey(key)
  return humanizeEnglishKey(key)
}
