// 术语以 qBittorrent 官方 src/lang/qbittorrent_zh_CN.ts（OptionsDialog）为基准。
const ZH_PREFERENCE_LABELS: Record<string, string> = {
  locale: "界面语言",
  app_instance_name: "应用程序实例名称",
  confirm_torrent_deletion: "删除 Torrent 前显示确认对话框",
  confirm_torrent_recheck: "重新检查 Torrent 前显示确认对话框",
  delete_torrent_content_files: "删除 Torrent 时同时删除内容文件",
  performance_warning: "显示性能警告",
  status_bar_external_ip: "在状态栏显示外部 IP 地址",
  save_path: "默认保存路径",
  temp_path_enabled: "启用未完成文件目录",
  temp_path: "未完成文件保存路径",
  scan_dirs: "自动监控目录",
  export_dir: "复制种子文件到指定目录",
  export_dir_fin: "下载完成后复制种子文件到指定目录",
  create_subfolder_enabled: "创建种子名称子目录",
  start_paused_enabled: "添加种子后保持停止",
  preallocate_all: "预分配所有文件空间",
  incomplete_files_ext: "未完成文件添加 .!qB 后缀",
  auto_tmm_enabled: "启用自动种子管理",
  torrent_changed_tmm_enabled: "种子变化时重新定位文件",
  save_path_changed_tmm_enabled: "默认路径变化时重新定位文件",
  category_changed_tmm_enabled: "分类变化时重新定位文件",
  use_category_paths_in_manual_mode: "在手动模式中使用分类路径",
  torrent_content_layout: "Torrent 内容布局",
  torrent_stop_condition: "Torrent 停止条件",
  add_stopped_enabled: "添加 Torrent 时不自动开始下载",
  add_to_top_of_queue: "将新 Torrent 添加到队列顶部",
  auto_delete_mode: "添加后删除 .torrent 文件",
  use_unwanted_folder: "将不需要的文件放入 .unwanted 文件夹",
  excluded_file_names_enabled: "排除指定名称的文件",
  excluded_file_names: "排除的文件名称",
  torrent_file_size_limit: "Torrent 文件大小限制",
  torrent_files_backup_enabled: "备份 Torrent 文件",
  torrent_files_backup_dir: "Torrent 文件备份目录",
  torrent_files_finished_backup_dir_enabled: "完成后备份 Torrent 文件",
  torrent_files_finished_backup_dir: "已完成 Torrent 文件备份目录",
  remove_torrent_file_backup: "删除 Torrent 时移除备份文件",
  merge_trackers: "合并同一地址的 Tracker",
  mark_of_the_web: "为下载文件添加网络来源标记",
  queueing_enabled: "启用种子队列",
  max_active_downloads: "最大活动下载数",
  max_active_uploads: "最大活动做种数",
  max_active_torrents: "最大活动种子数",
  max_active_checking_torrents: "最大活动检查 Torrent 数",
  dont_count_slow_torrents: "慢速种子不计入队列限制",
  slow_torrent_dl_rate_threshold: "慢速下载判定速度",
  slow_torrent_ul_rate_threshold: "慢速上传判定速度",
  slow_torrent_inactive_timer: "慢速种子判定时间",
  max_ratio_enabled: "启用分享率限制",
  max_ratio: "最大分享率",
  max_ratio_act: "达到分享率限制后的操作",
  max_seeding_time_enabled: "启用做种时间限制",
  max_seeding_time: "最长做种时间",
  max_seeding_time_limit_act: "达到做种时间限制后的操作",
  max_inactive_seeding_time_enabled: "启用非活动做种时间限制",
  max_inactive_seeding_time: "最大非活动做种时间",
  share_limits_mode: "分享限制条件",
  listen_port: "传入连接监听端口",
  upnp: "启用 UPnP / NAT-PMP 端口映射",
  random_port: "启动时随机选择监听端口",
  ssl_enabled: "启用备用 HTTPS 监听端口",
  ssl_listen_port: "备用 HTTPS 监听端口",
  dl_limit: "全局下载速度限制",
  up_limit: "全局上传速度限制",
  alt_dl_limit: "备用下载速度限制",
  alt_up_limit: "备用上传速度限制",
  scheduler_enabled: "启用备用速度计划",
  schedule_from_hour: "计划开始小时",
  schedule_from_min: "计划开始分钟",
  schedule_to_hour: "计划结束小时",
  schedule_to_min: "计划结束分钟",
  scheduler_days: "备用速度计划日期",
  dht: "启用分布式哈希表（DHT）",
  pex: "启用用户交换（PeX）",
  lsd: "启用本地用户发现（LSD）",
  encryption: "连接加密模式",
  anonymous_mode: "启用匿名模式",
  proxy_type: "代理类型",
  proxy_ip: "代理服务器地址",
  proxy_port: "代理服务器端口",
  proxy_auth_enabled: "启用代理身份验证",
  proxy_username: "代理用户名",
  proxy_password: "代理密码",
  proxy_hostname_lookup: "通过代理查找主机名",
  proxy_bittorrent: "将代理用于 BitTorrent",
  proxy_misc: "将代理用于常规用途",
  proxy_rss: "将代理用于 RSS",
  proxy_peer_connections: "通过代理连接用户",
  proxy_torrents_only: "仅将代理用于种子连接",
  ip_filter_enabled: "启用 IP 过滤",
  ip_filter_path: "IP 过滤规则文件",
  ip_filter_trackers: "将 IP 过滤应用到 Tracker",
  banned_IPs: "已封禁的 IP 地址",
  add_trackers_enabled: "自动添加 Tracker",
  add_trackers: "自动添加的 Tracker 列表",
  add_trackers_from_url_enabled: "从网址自动添加 Tracker",
  add_trackers_url: "Tracker 列表网址",
  add_trackers_url_list: "从网址获取的 Tracker 列表",
  announce_to_all_tiers: "向所有 Tracker 层级汇报",
  announce_to_all_trackers: "向所有 Tracker 汇报",
  announce_ip: "向 Tracker 汇报的 IP 地址",
  announce_port: "向 Tracker 汇报的端口",
  max_concurrent_http_announces: "最大并发 HTTP 汇报数",
  reannounce_when_address_changed: "IP 或端口变化时重新汇报",
  validate_https_tracker_certificate: "验证 HTTPS Tracker 证书",
  ssrf_mitigation: "启用服务器端请求伪造缓解措施",
  block_peers_on_privileged_ports: "阻止使用特权端口的用户",
  dht_bootstrap_nodes: "DHT 引导节点",
  web_ui_address: "WebUI 监听地址",
  web_ui_port: "WebUI 监听端口",
  web_ui_username: "WebUI 用户名",
  web_ui_password: "WebUI 密码",
  web_ui_api_key: "WebUI 接口密钥",
  web_ui_https_cert_path: "WebUI HTTPS 证书路径",
  web_ui_https_key_path: "WebUI HTTPS 私钥路径",
  web_ui_upnp: "为 WebUI 启用 UPnP / NAT-PMP",
  web_ui_csrf_protection_enabled: "启用 WebUI 跨站请求伪造防护",
  web_ui_clickjacking_protection_enabled: "启用 WebUI 点击劫持防护",
  web_ui_host_header_validation_enabled: "启用 WebUI 主机头验证",
  web_ui_domain_list: "WebUI 允许的域名列表",
  web_ui_secure_cookie_enabled: "启用 WebUI 安全 Cookie",
  web_ui_max_auth_fail_count: "WebUI 最大登录失败次数",
  web_ui_ban_duration: "WebUI 登录封禁时长",
  web_ui_session_timeout: "WebUI 会话超时时间",
  web_ui_sessions_count_limit: "WebUI 最大活动会话数",
  web_ui_reverse_proxy_enabled: "启用反向代理支持",
  web_ui_reverse_proxies_list: "可信反向代理列表",
  web_ui_use_custom_http_headers_enabled: "启用自定义 HTTP 标头",
  web_ui_custom_http_headers: "自定义 HTTP 标头",
  alternative_webui_enabled: "启用备用 WebUI",
  alternative_webui_path: "备用 WebUI 文件路径",
  use_https: "启用 HTTPS",
  ssl_key: "HTTPS 私钥路径",
  ssl_cert: "HTTPS 证书路径",
  bypass_local_auth: "本机访问跳过身份验证",
  bypass_auth_subnet_whitelist_enabled: "允许指定网段跳过身份验证",
  bypass_auth_subnet_whitelist: "免身份验证网段白名单",
  dyndns_enabled: "启用动态域名服务",
  dyndns_service: "动态域名服务商",
  dyndns_username: "动态域名用户名",
  dyndns_password: "动态域名密码",
  dyndns_domain: "动态域名",
  rss_processing_enabled: "启用 RSS 种子下载器",
  rss_refresh_interval: "RSS 刷新间隔",
  rss_fetch_delay: "RSS 文章获取延迟",
  rss_max_articles_per_feed: "每个 RSS 源最大文章数",
  rss_auto_downloading_enabled: "启用 RSS 自动下载",
  rss_download_repack_proper_episodes: "下载重发版与修正版剧集",
  rss_smart_episode_filters: "RSS 智能剧集过滤器",
  mail_notification_enabled: "启用邮件通知",
  mail_notification_sender: "邮件通知发件人",
  mail_notification_email: "邮件通知收件人",
  mail_notification_smtp: "邮件服务器地址",
  mail_notification_encryption_type: "SMTP 加密方式",
  mail_notification_ssl_enabled: "邮件服务器启用 SSL",
  mail_notification_auth_enabled: "邮件服务器启用身份验证",
  mail_notification_username: "邮件服务器用户名",
  mail_notification_password: "邮件服务器密码",
  autorun_enabled: "种子完成后运行外部程序",
  autorun_program: "种子完成后运行的程序",
  autorun_on_torrent_added_enabled: "添加 Torrent 后运行外部程序",
  autorun_on_torrent_added_program: "添加 Torrent 后运行的程序",
  recheck_completed_torrents: "完成后重新校验种子",
  resolve_peer_countries: "解析用户所在国家或地区",
  resolve_peer_host_names: "解析用户主机名",
  refresh_interval: "界面数据刷新间隔",
  save_resume_data_interval: "保存恢复数据的间隔",
  save_statistics_interval: "保存统计数据的间隔",
  resume_data_storage_type: "恢复数据存储类型",
  torrent_content_remove_option: "Torrent 内容删除方式",
  checking_memory_use: "检查 Torrent 时的内存使用上限",
  async_io_threads: "异步输入输出线程数",
  hashing_threads: "哈希校验线程数",
  file_pool_size: "文件池大小",
  disk_cache: "磁盘缓存大小",
  disk_cache_ttl: "磁盘缓存保留时间",
  disk_queue_size: "磁盘队列大小",
  disk_io_type: "磁盘输入输出类型",
  disk_io_read_mode: "磁盘输入输出读取模式",
  disk_io_write_mode: "磁盘输入输出写入模式",
  enable_os_cache: "启用操作系统磁盘缓存",
  enable_coalesce_read_write: "合并磁盘读写操作",
  enable_piece_extent_affinity: "启用分片范围亲和性",
  enable_upload_suggestions: "发送上传分片建议",
  memory_working_set_limit: "内存工作集限制",
  outgoing_ports_min: "传出连接最小端口",
  outgoing_ports_max: "传出连接最大端口",
  max_connec: "全局最大连接数",
  max_connec_per_torrent: "单个种子最大连接数",
  max_uploads: "全局最大上传槽位数",
  max_uploads_per_torrent: "单个种子最大上传槽位数",
  socket_backlog_size: "套接字等待队列大小",
  socket_receive_buffer_size: "套接字接收缓冲区大小",
  socket_send_buffer_size: "套接字发送缓冲区大小",
  send_buffer_watermark: "发送缓冲区上限",
  send_buffer_low_watermark: "发送缓冲区下限",
  send_buffer_watermark_factor: "发送缓冲区增长系数",
  request_queue_size: "请求队列大小",
  peer_tos: "用户连接服务类型标记",
  peer_turnover: "用户连接轮换比例",
  peer_turnover_cutoff: "用户连接轮换阈值",
  peer_turnover_interval: "用户连接轮换间隔",
  connection_speed: "每秒连接尝试次数",
  hostname_cache_ttl: "主机名缓存有效期",
  idn_support_enabled: "启用国际化域名支持",
  enable_multi_connections_from_same_ip: "允许来自同一 IP 地址的多个连接",
  enable_multi_connections_from_same_peer_id: "允许来自同一用户标识的多个连接",
  seeding_outgoing_connections: "做种时建立传出连接",
  bittorrent_protocol: "BitTorrent 传输协议",
  limit_utp_rate: "将速度限制应用到 µTP",
  limit_tcp_overhead: "将速度限制应用到 TCP 开销",
  limit_lan_peers: "将速度限制应用到局域网用户",
  utp_tcp_mixed_mode: "µTP 与 TCP 混合模式算法",
  upload_choking_algorithm: "上传阻塞算法",
  upload_slots_behavior: "上传槽位分配方式",
  stop_tracker_timeout: "停止 Tracker 的超时时间",
  enable_embedded_tracker: "启用内置 Tracker",
  embedded_tracker_port: "内置 Tracker 端口",
  embedded_tracker_port_forwarding: "为内置 Tracker 启用端口转发",
  i2p_enabled: "启用匿名网络支持",
  i2p_address: "匿名网络路由器地址",
  i2p_port: "匿名网络路由器端口",
  i2p_mixed_mode: "启用匿名网络混合模式",
  i2p_inbound_quantity: "匿名网络入站隧道数量",
  i2p_inbound_length: "匿名网络入站隧道长度",
  i2p_outbound_quantity: "匿名网络出站隧道数量",
  i2p_outbound_length: "匿名网络出站隧道长度",
  current_network_interface: "绑定的网络接口",
  current_interface_name: "当前网络接口名称",
  current_interface_address: "绑定到可选 IP 地址",
  upnp_lease_duration: "UPnP 租约时长",
  ignore_ssl_errors: "忽略 SSL 错误",
  bdecode_depth_limit: "BDecode 最大递归深度",
  bdecode_token_limit: "BDecode 最大令牌数",
  python_executable_path: "Python 可执行文件路径",
  file_log_enabled: "启用文件日志",
  file_log_path: "日志文件路径",
  file_log_backup_enabled: "备份旧日志文件",
  file_log_delete_old: "删除旧日志文件",
  file_log_age: "日志文件保留时间",
  file_log_age_type: "日志文件保留时间单位",
  file_log_max_size: "日志文件最大大小",
}

interface PreferenceOptionTranslation {
  value: string | number
  en: string
  zh: string
}

export interface PreferenceOption {
  value: string | number
  label: string
}

const PREFERENCE_OPTIONS: Record<string, readonly PreferenceOptionTranslation[]> = {
  bittorrent_protocol: [
    { value: 0, en: "TCP and μTP", zh: "TCP 和 μTP" },
    { value: 1, en: "TCP", zh: "TCP" },
    { value: 2, en: "μTP", zh: "μTP" },
  ],
  scheduler_days: [
    { value: 0, en: "Every day", zh: "每天" },
    { value: 1, en: "Weekdays", zh: "工作日" },
    { value: 2, en: "Weekends", zh: "周末" },
    { value: 3, en: "Monday", zh: "星期一" },
    { value: 4, en: "Tuesday", zh: "星期二" },
    { value: 5, en: "Wednesday", zh: "星期三" },
    { value: 6, en: "Thursday", zh: "星期四" },
    { value: 7, en: "Friday", zh: "星期五" },
    { value: 8, en: "Saturday", zh: "星期六" },
    { value: 9, en: "Sunday", zh: "星期日" },
  ],
  encryption: [
    { value: 0, en: "Allow encryption", zh: "允许加密" },
    { value: 1, en: "Require encryption", zh: "强制加密" },
    { value: 2, en: "Disable encryption", zh: "禁用加密" },
  ],
  proxy_type: [
    { value: "None", en: "None", zh: "无" },
    { value: "HTTP", en: "HTTP", zh: "HTTP" },
    { value: "SOCKS5", en: "SOCKS5", zh: "SOCKS5" },
    { value: "SOCKS4", en: "SOCKS4", zh: "SOCKS4" },
  ],
  dyndns_service: [
    { value: 0, en: "DynDNS", zh: "DynDNS" },
    { value: 1, en: "NO-IP", zh: "NO-IP" },
  ],
  max_ratio_act: [
    { value: 0, en: "Stop torrent", zh: "停止 Torrent" },
    { value: 1, en: "Remove torrent", zh: "移除 Torrent" },
    { value: 3, en: "Remove torrent and its files", zh: "删除 Torrent 及所属文件" },
    { value: 2, en: "Enable super seeding for torrent", zh: "为 Torrent 启用超级做种" },
  ],
  share_limits_mode: [
    { value: "MatchAny", en: "When any condition is met", zh: "满足任一条件时" },
    { value: "MatchAll", en: "When all conditions are met", zh: "满足全部条件时" },
  ],
  upload_slots_behavior: [
    { value: 0, en: "Fixed slots", zh: "固定窗口数" },
    { value: 1, en: "Upload rate based", zh: "基于上传速度" },
  ],
  upload_choking_algorithm: [
    { value: 0, en: "Round-robin", zh: "轮流上传" },
    { value: 1, en: "Fastest upload", zh: "最快上传" },
    { value: 2, en: "Anti-leech", zh: "反吸血" },
  ],
  utp_tcp_mixed_mode: [
    { value: 0, en: "Prefer TCP", zh: "优先使用 TCP" },
    { value: 1, en: "Peer proportional (throttles TCP)", zh: "按用户比重（抑制 TCP）" },
  ],
  disk_io_type: [
    { value: 0, en: "Default", zh: "默认" },
    { value: 1, en: "Memory mapped files", zh: "内存映射文件" },
    { value: 2, en: "POSIX-compliant", zh: "遵循 POSIX" },
    { value: 3, en: "Simple pread/pwrite", zh: "简单 pread/pwrite" },
    { value: 4, en: "Pread/pwrite", zh: "Pread/pwrite" },
  ],
  disk_io_read_mode: [
    { value: 0, en: "Disable OS cache", zh: "禁用操作系统缓存" },
    { value: 1, en: "Enable OS cache", zh: "启用操作系统缓存" },
  ],
  disk_io_write_mode: [
    { value: 0, en: "Disable OS cache", zh: "禁用操作系统缓存" },
    { value: 1, en: "Enable OS cache", zh: "启用操作系统缓存" },
    { value: 2, en: "Write-through", zh: "连续写入" },
  ],
  file_log_age_type: [
    { value: 0, en: "Days", zh: "天" },
    { value: 1, en: "Months", zh: "月" },
    { value: 2, en: "Years", zh: "年" },
  ],
  torrent_content_layout: [
    { value: "Original", en: "Original", zh: "原始" },
    { value: "Subfolder", en: "Create subfolder", zh: "创建子文件夹" },
    { value: "NoSubfolder", en: "Don't create subfolder", zh: "不创建子文件夹" },
  ],
  torrent_stop_condition: [
    { value: "None", en: "None", zh: "无" },
    { value: "MetadataReceived", en: "Metadata received", zh: "已收到元数据" },
    { value: "FilesChecked", en: "Files checked", zh: "文件已被检查" },
  ],
  resume_data_storage_type: [
    { value: "Legacy", en: "Fastresume files", zh: "快速恢复文件" },
    { value: "SQLite", en: "SQLite database (experimental)", zh: "SQLite 数据库（实验性功能）" },
  ],
  torrent_content_remove_option: [
    { value: "Delete", en: "Delete files permanently", zh: "永久删除文件" },
    { value: "MoveToTrash", en: "Move files to trash (if possible)", zh: "移动文件到回收站（如果可能）" },
  ],
  mail_notification_encryption_type: [
    { value: "None", en: "None", zh: "无" },
    { value: "STARTTLS", en: "STARTTLS", zh: "STARTTLS" },
    { value: "SMTPS", en: "SMTPS", zh: "SMTPS" },
  ],
}

const LEGACY_PROXY_OPTIONS: readonly PreferenceOptionTranslation[] = [
  { value: -1, en: "None", zh: "无" },
  { value: 0, en: "HTTP", zh: "HTTP" },
  { value: 1, en: "SOCKS5", zh: "SOCKS5" },
  { value: 2, en: "HTTP with authentication", zh: "HTTP（需要身份验证）" },
]

const ZH_TOKEN_LABELS: Record<string, string> = {
  enabled: "启用",
  disabled: "禁用",
  path: "路径",
  port: "端口",
  address: "地址",
  username: "用户名",
  password: "密码",
  interval: "间隔",
  timeout: "超时",
  limit: "限制",
  limits: "限制",
  max: "最大",
  min: "最小",
  download: "下载",
  upload: "上传",
  torrents: "种子",
  torrent: "种子",
  peers: "用户",
  peer: "用户",
  queue: "队列",
  cache: "缓存",
  disk: "磁盘",
  network: "网络",
  connection: "连接",
  connections: "连接",
  notification: "通知",
  authentication: "身份验证",
  auth: "身份验证",
  protection: "防护",
  required: "需要",
  auto: "自动",
  random: "随机",
  default: "默认",
  alternative: "备用",
  secure: "安全",
  local: "本地",
  global: "全局",
  ratio: "分享率",
  seeding: "做种",
  time: "时间",
  hours: "小时",
  minutes: "分钟",
  days: "日期",
  threads: "线程数",
  size: "大小",
  mode: "模式",
  type: "类型",
  program: "程序",
  processing: "处理",
}

function humanizeEnglishKey(key: string): string {
  return key
    .split("_")
    .filter(Boolean)
    .map((token) => token.charAt(0).toUpperCase() + token.slice(1))
    .join(" ")
}

function humanizeChineseKey(key: string): string {
  const translated = key
    .split("_")
    .filter(Boolean)
    .map((token) => ZH_TOKEN_LABELS[token] ?? token.toUpperCase())
    .join(" · ")
  return `高级设置：${translated}`
}

export function getPreferenceLabel(key: string, locale: "en" | "zh"): string {
  if (locale === "zh") return ZH_PREFERENCE_LABELS[key] ?? humanizeChineseKey(key)
  return humanizeEnglishKey(key)
}

export function getPreferenceOptions(
  key: string,
  locale: "en" | "zh",
  currentValue?: string | number,
): readonly PreferenceOption[] | undefined {
  const translations = key === "proxy_type" && typeof currentValue === "number"
    ? LEGACY_PROXY_OPTIONS
    : PREFERENCE_OPTIONS[key]

  return translations?.map((option) => ({
    value: option.value,
    label: locale === "zh" ? option.zh : option.en,
  }))
}
